### PR TITLE
Fixingtests

### PR DESCRIPTION
**Pull request by ddigioia**
1) made it so the new words don't fall into other word divs when adding them to a list
2) made the newest words added to a list show uo first
3) moved list delete button

### CODE REVIEW

**Comment by trivett** [comment]
Thank you Derek! I'll check out your code and see how you managed to fix that.

**Comment by ddigioia** [comment]
For some reason, a few words get added twice to a list whereas other dont

**Comment by ddigioia** [comment]
1) touched up timer to look a little nicer
2) took pause buttons out, seemed unnecessary to have one

**Comment by ddigioia** [comment]
tweet button is not working, any ideas?

**Comment by trivett** [comment]
Whoops. Didn't mean to merge that. Will fix asap.

**Pull request merged**
